[tool.poetry]
name = "django-schedules"
version = "1.1.0"
description = "A Django app to define routines that should run periodically"
authors = ["sedrubal <dev@sedrubal.de>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Django = ">=4.0"
django-appconf = ">=1.0.5"
tabulate = ">=0.9.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.0"
ruff = "^0.1.5"
isort = "^5.12.0"
pre-commit = "^3.5.0"
black = "^23.11.0"
pylint = "^3.0.2"
types-tabulate = "^0.9.0.3"
pyre-check = "^0.9.19"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
