[build-system]
requires = ["setuptools >= 40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "nginx_log_stats"
version = "1.22"
description = "Search through NGINX logs with advanced filters and support for displaying analytics about your selected log entries"
readme = "README.md"

authors = ["Quinn Patwardhan <quinn@qpxdesign.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.scripts]
ngxav = "nginx_log_stats:main"
