[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "base_conversion_kit"
version = "1.0.7"
authors = [
  { name="Pavlos Orfanidis", email="pavlos@orfanidis.net.gr" },
]
description = "Perform operations with numbers in different bases"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
