[tool.poetry]
name = "func3_lib"
version = "0.0.2"
description = "Three functions func3_lib 'transpose2d', 'window1d' and 'convolution2d'."
authors = ["LinasT"]
license = "MIT"
readme = "README.md"
packages = [{include = "func3_lib"}]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
setuptools = "^68.2.2"
wheel = "^0.41.3"
numpy = "^1.26.2"
twine = "^4.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
