[project]
name = "auto-config"
dynamic = []
description = "auto config for my personal devices"
authors = [
    { name = "Zhan Rongrui", email = "2742392377@qq.com" },
]
dependencies = [
    "typer",
]
requires-python = ">=3.11"
readme = "README.md"
version = "0.0.5"

[project.license]
text = "MIT"

[project.optional-dependencies]

[project.scripts]
auto-config = "auto_config.__main__:app"

[tool.pdm.version]
source = "scm"
write_to = "auto_config/__version__.py"
write_template = "__version__ = '{}'"

[tool.pdm.dev-dependencies]
test = [
    "pytest",
    "pytest-mock",
    "coverage",
    "libcst",
]

[tool.pdm.build]
excludes = [
    "./**/.git",
]
includes = [
    "auto_config",
]
source-includes = [
    "tests",
    "LICENSE",
    "README.md",
]
editable-backend = "path"

[tool.ruff]
line-length = 120
extend-select = [
    "I",
    "B",
    "C4",
    "PGH",
    "RUF",
    "W",
    "YTT",
]
src = [
    "auto_config",
    "tests",
]
exclude = [
    "tests/fixtures",
]
target-version = "py39"
ignore = [
    "F841",
]

[tool.ruff.isort]
known-first-party = [
    "auto_config",
]
required-imports = [
    "from __future__ import annotations",
]

[tool.ruff.per-file-ignores]
"__init__.py" = [
    "F401",
]

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
