[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "aifund"
version = "0.0.8"
authors = [
    { name = "tiano", email = "silence_hgt@163.com" },
]
description = "AIfund 是基于 Python 的基金量化工具"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/silenceTiano/aifund"
"Bug Tracker" = "https://github.com/silenceTiano/aifund/issues"