[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "power_vision_AI_of_the_tiger"
version = "0.0.12"
authors = [
  { name="Alexandre A." },
  { name="Aline C." },
  { name="Thibault F." },
]
description = "A package to detect falls."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: POSIX :: Linux",
]
# dependencies = [
#     "matplotlib==3.8.1",
#     "mediapipe==0.10.8",
#     "numpy==1.26.2",
#     "opencv-python==4.8.1.78",
#     "Pillow==10.1.0",
#     "requests==2.31.0",
#     "scikit-learn==1.3.2",
#     "tqdm==4.66.1"
# ]
dependencies = [
    "mediapipe",
    "opencv-python",
    "Pillow",
    "scikit-learn",
    "requests",
    "tqdm",
    "pandas",
    "moviepy"
]

[project.urls]
"GitHub" = "https://github.com/aappolaire/power_vision_AI_of_the_tiger"
"Bug Tracker" = "https://github.com/aappolaire/power_vision_AI_of_the_tiger/issues"

[project.scripts]
power_vision_AI_of_the_tiger_classify = "power_vision_AI_of_the_tiger.classify_video:main"

