[project]
name = "slingshot-ai"
version = "0.0.27rc59"

[tool.poetry]
name = "slingshot-ai"
version = "0.0.27rc59"
description = "Slingshot Python SDK"
authors = ["Slingshot AI <service-account@slingshot.xyz>"]
packages = [{ include = "slingshot", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = ">=3.8.1"
urllib3 = ">=1.26.11"
pydantic = ">=2.0.0,<2.4.0"
pydantic-settings = ">=2.0.0,<3"
typer = { extras = ["all"], version = ">=0.7.0" }
requests = ">=2.28.1"
sh = ">=1.14.3"
pyyaml = ">=6.0"
"ruamel.yaml" = ">=0.17.0"
simple-term-menu = ">=1.6.0"
deepdiff = ">=6.3.0"
tqdm = ">=4.63.0"
sentry-sdk = ">=1.16.0"
backoff = ">=2.0.0"
openai = ">=0.27.8"
fastapi = ">=0.100.0"
uvicorn = { extras = ["standard"], version = ">=0.12.0" }
pathspec = ">=0.10.1"

[tool.poetry.scripts]
slingshot = "slingshot.cli.main:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
