[package]
name = "pyfilon"
version = "1.0.3"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyfilon"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
filon = {path = "filon-rs"}
