[project]
name = "aglog"
version = "0.1.2"
description = "Logging support tools for python"
authors = [{ name = "agarichan", email = "ag4r1chan@gmail.com" }]
dependencies = ["PyYAML>=6.0.1", "typing_extensions>=4.8.0", "Pygments>=2.16.1"]
readme = "README.md"
requires-python = ">= 3.10"
license = "MIT"
urls = { Repository = "https://github.com/agarichan/aglog" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=7.4.3",
    "ipykernel>=6.26.0",
    "ruff>=0.1.5",
    "pytest-cov>=4.1.0",
    "freezegun>=1.2.2",
]

[tool.rye.scripts]
lint = { chain = ["lint:ruff-format", "lint:ruff-check"] }
test = { chain = ["test:pytest", "test:delete-dotfile"] }
"lint:ruff-format" = "ruff format ."
"lint:ruff-check" = "ruff --fix ."
"test:pytest" = "pytest --cov=src --cov-report=term-missing --cov-report=xml tests"
"test:delete-dotfile" = "rm -rf .coverage"


[tool.ruff]
target-version = "py310"
line-length = 240
select = ["ALL"]
ignore = ["D", "ISC001", "COM812", "ANN401", "PGH003"]
src = ["src", "utils"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"tests/*" = ["INP001", "S101", "ANN", "A001", "N802", "ARG", "PLR"]
"*.ipynb" = ["E402", "I001"]

[tool.pytest.ini_options]
norecursedirs = "tests/utils"

[tool.hatch.metadata]
allow-direct-references = true
