[build-system]
requires = ["setuptools>=61.0","numpy","matplotlib"]
build-backend="setuptools.build_meta"
[project]
name = "txt_sky"
version = "1.2.2"
authors = [
  { name="Sky Vega Yang", email="xjgis@126.com" },
]
description = "A package for writing txt"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
