[tool.poetry]
name = "archive-strategy"
version = "0.1.4.0"
description = ""
authors = ["Pieter Paulussen <pieterpaulussen@code-source.be>"]
readme = "README.md"
packages = [{include = "archive_strategy"}]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^13.6.0"
click = "^8.1.7"
python-dateutil = "^2.8.2"

[tool.poetry.scripts]
archive-strategy = "archive_strategy.main:main"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
freezegun = "^1.2.2"
black = "^23.11.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
pylint = "^3.0.2"
pre-commit = "^3.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
